/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_utils.h"

static const char* CMockString_Debug_Print = "Debug_Print";
static const char* CMockString_msg = "msg";

typedef struct _CMOCK_Debug_Print_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  const char* Expected_msg;

} CMOCK_Debug_Print_CALL_INSTANCE;

static struct mock_utilsInstance
{
  char Debug_Print_IgnoreBool;
  char Debug_Print_CallbackBool;
  CMOCK_Debug_Print_CALLBACK Debug_Print_CallbackFunctionPointer;
  int Debug_Print_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE Debug_Print_CallInstance;
} Mock;


void mock_utils_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.Debug_Print_CallInstance;
  if (Mock.Debug_Print_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_Debug_Print);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.Debug_Print_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_utils_Init(void)
{
  mock_utils_Destroy();
}

void mock_utils_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Debug_Print(const char* msg)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Debug_Print_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_Debug_Print);
  cmock_call_instance = (CMOCK_Debug_Print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Debug_Print_CallInstance);
  Mock.Debug_Print_CallInstance = CMock_Guts_MemNext(Mock.Debug_Print_CallInstance);
  if (Mock.Debug_Print_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.Debug_Print_CallbackBool &&
      Mock.Debug_Print_CallbackFunctionPointer != NULL)
  {
    Mock.Debug_Print_CallbackFunctionPointer(msg, Mock.Debug_Print_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_Debug_Print,CMockString_msg);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_msg, msg, cmock_line, CMockStringMismatch);
  }
  if (Mock.Debug_Print_CallbackFunctionPointer != NULL)
  {
    Mock.Debug_Print_CallbackFunctionPointer(msg, Mock.Debug_Print_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_Debug_Print(CMOCK_Debug_Print_CALL_INSTANCE* cmock_call_instance, const char* msg);
void CMockExpectParameters_Debug_Print(CMOCK_Debug_Print_CALL_INSTANCE* cmock_call_instance, const char* msg)
{
  cmock_call_instance->Expected_msg = msg;
}

void Debug_Print_CMockIgnore(void)
{
  Mock.Debug_Print_IgnoreBool = (char)1;
}

void Debug_Print_CMockStopIgnore(void)
{
  Mock.Debug_Print_IgnoreBool = (char)0;
}

void Debug_Print_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* msg)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Debug_Print_CALL_INSTANCE));
  CMOCK_Debug_Print_CALL_INSTANCE* cmock_call_instance = (CMOCK_Debug_Print_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.Debug_Print_CallInstance = CMock_Guts_MemChain(Mock.Debug_Print_CallInstance, cmock_guts_index);
  Mock.Debug_Print_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_Debug_Print(cmock_call_instance, msg);
}

void Debug_Print_AddCallback(CMOCK_Debug_Print_CALLBACK Callback)
{
  Mock.Debug_Print_IgnoreBool = (char)0;
  Mock.Debug_Print_CallbackBool = (char)1;
  Mock.Debug_Print_CallbackFunctionPointer = Callback;
}

void Debug_Print_Stub(CMOCK_Debug_Print_CALLBACK Callback)
{
  Mock.Debug_Print_IgnoreBool = (char)0;
  Mock.Debug_Print_CallbackBool = (char)0;
  Mock.Debug_Print_CallbackFunctionPointer = Callback;
}

