/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_UTILS_H
#define _MOCK_UTILS_H

#include "unity.h"
#include "utils.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

#ifdef __cplusplus
extern "C" {
#endif

void mock_utils_Init(void);
void mock_utils_Destroy(void);
void mock_utils_Verify(void);




#define Debug_Print_IgnoreAndReturn(cmock_retval) TEST_FAIL_MESSAGE("Debug_Print requires _Ignore (not AndReturn)");
#define Debug_Print_Ignore() Debug_Print_CMockIgnore()
void Debug_Print_CMockIgnore(void);
#define Debug_Print_StopIgnore() Debug_Print_CMockStopIgnore()
void Debug_Print_CMockStopIgnore(void);
#define Debug_Print_ExpectAndReturn(msg, cmock_retval) TEST_FAIL_MESSAGE("Debug_Print requires _Expect (not AndReturn)");
#define Debug_Print_Expect(msg) Debug_Print_CMockExpect(__LINE__, msg)
void Debug_Print_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* msg);
typedef void (* CMOCK_Debug_Print_CALLBACK)(const char* msg, int cmock_num_calls);
void Debug_Print_AddCallback(CMOCK_Debug_Print_CALLBACK Callback);
void Debug_Print_Stub(CMOCK_Debug_Print_CALLBACK Callback);
#define Debug_Print_StubWithCallback Debug_Print_Stub

#ifdef __cplusplus
}
#endif

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
