// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v2/types.proto
// Original file comments:
// *******************************************************************************
// Copyright (c) 2024 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// This program and the accompanying materials are made available under the
// terms of the Apache License 2.0 which is available at
// http://www.apache.org/licenses/LICENSE-2.0
//
// SPDX-License-Identifier: Apache-2.0
// ******************************************************************************
//
#ifndef GRPC_kuksa_2fval_2fv2_2ftypes_2eproto__INCLUDED
#define GRPC_kuksa_2fval_2fv2_2ftypes_2eproto__INCLUDED

#include "kuksa/val/v2/types.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace kuksa {
namespace val {
namespace v2 {

}  // namespace v2
}  // namespace val
}  // namespace kuksa


#endif  // GRPC_kuksa_2fval_2fv2_2ftypes_2eproto__INCLUDED
