// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kuksa/val/v2/val.proto

#include "kuksa/val/v2/val.pb.h"
#include "kuksa/val/v2/val.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace kuksa {
namespace val {
namespace v2 {

static const char* VAL_method_names[] = {
  "/kuksa.val.v2.VAL/GetValue",
  "/kuksa.val.v2.VAL/GetValues",
  "/kuksa.val.v2.VAL/Subscribe",
  "/kuksa.val.v2.VAL/SubscribeById",
  "/kuksa.val.v2.VAL/Actuate",
  "/kuksa.val.v2.VAL/BatchActuate",
  "/kuksa.val.v2.VAL/ListMetadata",
  "/kuksa.val.v2.VAL/PublishValue",
  "/kuksa.val.v2.VAL/OpenProviderStream",
  "/kuksa.val.v2.VAL/GetServerInfo",
};

std::unique_ptr< VAL::Stub> VAL::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VAL::Stub> stub(new VAL::Stub(channel, options));
  return stub;
}

VAL::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetValue_(VAL_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetValues_(VAL_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(VAL_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SubscribeById_(VAL_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Actuate_(VAL_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_BatchActuate_(VAL_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListMetadata_(VAL_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PublishValue_(VAL_method_names[7], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenProviderStream_(VAL_method_names[8], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_GetServerInfo_(VAL_method_names[9], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VAL::Stub::GetValue(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::kuksa::val::v2::GetValueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::GetValueRequest, ::kuksa::val::v2::GetValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetValue_, context, request, response);
}

void VAL::Stub::async::GetValue(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest* request, ::kuksa::val::v2::GetValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::GetValueRequest, ::kuksa::val::v2::GetValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, std::move(f));
}

void VAL::Stub::async::GetValue(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest* request, ::kuksa::val::v2::GetValueResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValueResponse>* VAL::Stub::PrepareAsyncGetValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::GetValueResponse, ::kuksa::val::v2::GetValueRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValueResponse>* VAL::Stub::AsyncGetValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VAL::Stub::GetValues(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::kuksa::val::v2::GetValuesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::GetValuesRequest, ::kuksa::val::v2::GetValuesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetValues_, context, request, response);
}

void VAL::Stub::async::GetValues(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest* request, ::kuksa::val::v2::GetValuesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::GetValuesRequest, ::kuksa::val::v2::GetValuesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, std::move(f));
}

void VAL::Stub::async::GetValues(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest* request, ::kuksa::val::v2::GetValuesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValuesResponse>* VAL::Stub::PrepareAsyncGetValuesRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::GetValuesResponse, ::kuksa::val::v2::GetValuesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetValues_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValuesResponse>* VAL::Stub::AsyncGetValuesRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetValuesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::kuksa::val::v2::SubscribeResponse>* VAL::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void VAL::Stub::async::Subscribe(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest* request, ::grpc::ClientReadReactor< ::kuksa::val::v2::SubscribeResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeResponse>* VAL::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeResponse>* VAL::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::ClientReader< ::kuksa::val::v2::SubscribeByIdResponse>* VAL::Stub::SubscribeByIdRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(channel_.get(), rpcmethod_SubscribeById_, context, request);
}

void VAL::Stub::async::SubscribeById(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest* request, ::grpc::ClientReadReactor< ::kuksa::val::v2::SubscribeByIdResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeById_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeByIdResponse>* VAL::Stub::AsyncSubscribeByIdRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(channel_.get(), cq, rpcmethod_SubscribeById_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeByIdResponse>* VAL::Stub::PrepareAsyncSubscribeByIdRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(channel_.get(), cq, rpcmethod_SubscribeById_, context, request, false, nullptr);
}

::grpc::Status VAL::Stub::Actuate(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::kuksa::val::v2::ActuateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::ActuateRequest, ::kuksa::val::v2::ActuateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Actuate_, context, request, response);
}

void VAL::Stub::async::Actuate(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest* request, ::kuksa::val::v2::ActuateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::ActuateRequest, ::kuksa::val::v2::ActuateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Actuate_, context, request, response, std::move(f));
}

void VAL::Stub::async::Actuate(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest* request, ::kuksa::val::v2::ActuateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Actuate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ActuateResponse>* VAL::Stub::PrepareAsyncActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::ActuateResponse, ::kuksa::val::v2::ActuateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Actuate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ActuateResponse>* VAL::Stub::AsyncActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncActuateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VAL::Stub::BatchActuate(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::kuksa::val::v2::BatchActuateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::BatchActuateRequest, ::kuksa::val::v2::BatchActuateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_BatchActuate_, context, request, response);
}

void VAL::Stub::async::BatchActuate(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest* request, ::kuksa::val::v2::BatchActuateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::BatchActuateRequest, ::kuksa::val::v2::BatchActuateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchActuate_, context, request, response, std::move(f));
}

void VAL::Stub::async::BatchActuate(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest* request, ::kuksa::val::v2::BatchActuateResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_BatchActuate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::BatchActuateResponse>* VAL::Stub::PrepareAsyncBatchActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::BatchActuateResponse, ::kuksa::val::v2::BatchActuateRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_BatchActuate_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::BatchActuateResponse>* VAL::Stub::AsyncBatchActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncBatchActuateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VAL::Stub::ListMetadata(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::kuksa::val::v2::ListMetadataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::ListMetadataRequest, ::kuksa::val::v2::ListMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListMetadata_, context, request, response);
}

void VAL::Stub::async::ListMetadata(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest* request, ::kuksa::val::v2::ListMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::ListMetadataRequest, ::kuksa::val::v2::ListMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListMetadata_, context, request, response, std::move(f));
}

void VAL::Stub::async::ListMetadata(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest* request, ::kuksa::val::v2::ListMetadataResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ListMetadataResponse>* VAL::Stub::PrepareAsyncListMetadataRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::ListMetadataResponse, ::kuksa::val::v2::ListMetadataRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListMetadata_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ListMetadataResponse>* VAL::Stub::AsyncListMetadataRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListMetadataRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status VAL::Stub::PublishValue(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::kuksa::val::v2::PublishValueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::PublishValueRequest, ::kuksa::val::v2::PublishValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_PublishValue_, context, request, response);
}

void VAL::Stub::async::PublishValue(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest* request, ::kuksa::val::v2::PublishValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::PublishValueRequest, ::kuksa::val::v2::PublishValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PublishValue_, context, request, response, std::move(f));
}

void VAL::Stub::async::PublishValue(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest* request, ::kuksa::val::v2::PublishValueResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_PublishValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::PublishValueResponse>* VAL::Stub::PrepareAsyncPublishValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::PublishValueResponse, ::kuksa::val::v2::PublishValueRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_PublishValue_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::PublishValueResponse>* VAL::Stub::AsyncPublishValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPublishValueRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReaderWriter< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>* VAL::Stub::OpenProviderStreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>::Create(channel_.get(), rpcmethod_OpenProviderStream_, context);
}

void VAL::Stub::async::OpenProviderStream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::kuksa::val::v2::OpenProviderStreamRequest,::kuksa::val::v2::OpenProviderStreamResponse>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest,::kuksa::val::v2::OpenProviderStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_OpenProviderStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>* VAL::Stub::AsyncOpenProviderStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>::Create(channel_.get(), cq, rpcmethod_OpenProviderStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>* VAL::Stub::PrepareAsyncOpenProviderStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>::Create(channel_.get(), cq, rpcmethod_OpenProviderStream_, context, false, nullptr);
}

::grpc::Status VAL::Stub::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::kuksa::val::v2::GetServerInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::kuksa::val::v2::GetServerInfoRequest, ::kuksa::val::v2::GetServerInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetServerInfo_, context, request, response);
}

void VAL::Stub::async::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest* request, ::kuksa::val::v2::GetServerInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::kuksa::val::v2::GetServerInfoRequest, ::kuksa::val::v2::GetServerInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, std::move(f));
}

void VAL::Stub::async::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest* request, ::kuksa::val::v2::GetServerInfoResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetServerInfoResponse>* VAL::Stub::PrepareAsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::kuksa::val::v2::GetServerInfoResponse, ::kuksa::val::v2::GetServerInfoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetServerInfo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetServerInfoResponse>* VAL::Stub::AsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetServerInfoRaw(context, request, cq);
  result->StartCall();
  return result;
}

VAL::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::GetValueRequest, ::kuksa::val::v2::GetValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::GetValueRequest* req,
             ::kuksa::val::v2::GetValueResponse* resp) {
               return service->GetValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::GetValuesRequest, ::kuksa::val::v2::GetValuesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::GetValuesRequest* req,
             ::kuksa::val::v2::GetValuesResponse* resp) {
               return service->GetValues(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VAL::Service, ::kuksa::val::v2::SubscribeRequest, ::kuksa::val::v2::SubscribeResponse>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::SubscribeRequest* req,
             ::grpc::ServerWriter<::kuksa::val::v2::SubscribeResponse>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VAL::Service, ::kuksa::val::v2::SubscribeByIdRequest, ::kuksa::val::v2::SubscribeByIdResponse>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::SubscribeByIdRequest* req,
             ::grpc::ServerWriter<::kuksa::val::v2::SubscribeByIdResponse>* writer) {
               return service->SubscribeById(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::ActuateRequest, ::kuksa::val::v2::ActuateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::ActuateRequest* req,
             ::kuksa::val::v2::ActuateResponse* resp) {
               return service->Actuate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::BatchActuateRequest, ::kuksa::val::v2::BatchActuateResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::BatchActuateRequest* req,
             ::kuksa::val::v2::BatchActuateResponse* resp) {
               return service->BatchActuate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::ListMetadataRequest, ::kuksa::val::v2::ListMetadataResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::ListMetadataRequest* req,
             ::kuksa::val::v2::ListMetadataResponse* resp) {
               return service->ListMetadata(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::PublishValueRequest, ::kuksa::val::v2::PublishValueResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::PublishValueRequest* req,
             ::kuksa::val::v2::PublishValueResponse* resp) {
               return service->PublishValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[8],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< VAL::Service, ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::kuksa::val::v2::OpenProviderStreamResponse,
             ::kuksa::val::v2::OpenProviderStreamRequest>* stream) {
               return service->OpenProviderStream(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::GetServerInfoRequest, ::kuksa::val::v2::GetServerInfoResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VAL::Service* service,
             ::grpc::ServerContext* ctx,
             const ::kuksa::val::v2::GetServerInfoRequest* req,
             ::kuksa::val::v2::GetServerInfoResponse* resp) {
               return service->GetServerInfo(ctx, req, resp);
             }, this)));
}

VAL::Service::~Service() {
}

::grpc::Status VAL::Service::GetValue(::grpc::ServerContext* context, const ::kuksa::val::v2::GetValueRequest* request, ::kuksa::val::v2::GetValueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::GetValues(::grpc::ServerContext* context, const ::kuksa::val::v2::GetValuesRequest* request, ::kuksa::val::v2::GetValuesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::Subscribe(::grpc::ServerContext* context, const ::kuksa::val::v2::SubscribeRequest* request, ::grpc::ServerWriter< ::kuksa::val::v2::SubscribeResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::SubscribeById(::grpc::ServerContext* context, const ::kuksa::val::v2::SubscribeByIdRequest* request, ::grpc::ServerWriter< ::kuksa::val::v2::SubscribeByIdResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::Actuate(::grpc::ServerContext* context, const ::kuksa::val::v2::ActuateRequest* request, ::kuksa::val::v2::ActuateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::BatchActuate(::grpc::ServerContext* context, const ::kuksa::val::v2::BatchActuateRequest* request, ::kuksa::val::v2::BatchActuateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::ListMetadata(::grpc::ServerContext* context, const ::kuksa::val::v2::ListMetadataRequest* request, ::kuksa::val::v2::ListMetadataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::PublishValue(::grpc::ServerContext* context, const ::kuksa::val::v2::PublishValueRequest* request, ::kuksa::val::v2::PublishValueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::OpenProviderStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::kuksa::val::v2::OpenProviderStreamResponse, ::kuksa::val::v2::OpenProviderStreamRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::GetServerInfo(::grpc::ServerContext* context, const ::kuksa::val::v2::GetServerInfoRequest* request, ::kuksa::val::v2::GetServerInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kuksa
}  // namespace val
}  // namespace v2

