// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: val.proto

#include "val.pb.h"
#include "val.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace kuksa {
namespace val {
namespace v2 {

static const char* VAL_method_names[] = {
  "/kuksa.val.v2.VAL/GetValue",
  "/kuksa.val.v2.VAL/GetValues",
  "/kuksa.val.v2.VAL/Subscribe",
  "/kuksa.val.v2.VAL/SubscribeById",
  "/kuksa.val.v2.VAL/Actuate",
  "/kuksa.val.v2.VAL/ActuateStream",
  "/kuksa.val.v2.VAL/BatchActuate",
  "/kuksa.val.v2.VAL/ListMetadata",
  "/kuksa.val.v2.VAL/PublishValue",
  "/kuksa.val.v2.VAL/OpenProviderStream",
  "/kuksa.val.v2.VAL/GetServerInfo",
};

std::unique_ptr< VAL::Stub> VAL::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VAL::Stub> stub(new VAL::Stub(channel));
  return stub;
}

VAL::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetValue_(VAL_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetValues_(VAL_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Subscribe_(VAL_method_names[2], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_SubscribeById_(VAL_method_names[3], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_Actuate_(VAL_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ActuateStream_(VAL_method_names[5], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  , rpcmethod_BatchActuate_(VAL_method_names[6], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListMetadata_(VAL_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_PublishValue_(VAL_method_names[8], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_OpenProviderStream_(VAL_method_names[9], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  , rpcmethod_GetServerInfo_(VAL_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VAL::Stub::GetValue(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::kuksa::val::v2::GetValueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetValue_, context, request, response);
}

void VAL::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest* request, ::kuksa::val::v2::GetValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::GetValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest* request, ::kuksa::val::v2::GetValueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::GetValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::GetValueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValueResponse>* VAL::Stub::AsyncGetValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::GetValueResponse>::Create(channel_.get(), cq, rpcmethod_GetValue_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValueResponse>* VAL::Stub::PrepareAsyncGetValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::GetValueResponse>::Create(channel_.get(), cq, rpcmethod_GetValue_, context, request, false);
}

::grpc::Status VAL::Stub::GetValues(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::kuksa::val::v2::GetValuesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetValues_, context, request, response);
}

void VAL::Stub::experimental_async::GetValues(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest* request, ::kuksa::val::v2::GetValuesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::GetValues(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::GetValuesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::GetValues(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest* request, ::kuksa::val::v2::GetValuesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::GetValues(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::GetValuesResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetValues_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValuesResponse>* VAL::Stub::AsyncGetValuesRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::GetValuesResponse>::Create(channel_.get(), cq, rpcmethod_GetValues_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetValuesResponse>* VAL::Stub::PrepareAsyncGetValuesRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetValuesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::GetValuesResponse>::Create(channel_.get(), cq, rpcmethod_GetValues_, context, request, false);
}

::grpc::ClientReader< ::kuksa::val::v2::SubscribeResponse>* VAL::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void VAL::Stub::experimental_async::Subscribe(::grpc::ClientContext* context, ::kuksa::val::v2::SubscribeRequest* request, ::grpc::experimental::ClientReadReactor< ::kuksa::val::v2::SubscribeResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeResponse>* VAL::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeResponse>* VAL::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeResponse>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

::grpc::ClientReader< ::kuksa::val::v2::SubscribeByIdResponse>* VAL::Stub::SubscribeByIdRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(channel_.get(), rpcmethod_SubscribeById_, context, request);
}

void VAL::Stub::experimental_async::SubscribeById(::grpc::ClientContext* context, ::kuksa::val::v2::SubscribeByIdRequest* request, ::grpc::experimental::ClientReadReactor< ::kuksa::val::v2::SubscribeByIdResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeById_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeByIdResponse>* VAL::Stub::AsyncSubscribeByIdRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(channel_.get(), cq, rpcmethod_SubscribeById_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::kuksa::val::v2::SubscribeByIdResponse>* VAL::Stub::PrepareAsyncSubscribeByIdRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::SubscribeByIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::kuksa::val::v2::SubscribeByIdResponse>::Create(channel_.get(), cq, rpcmethod_SubscribeById_, context, request, false, nullptr);
}

::grpc::Status VAL::Stub::Actuate(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::kuksa::val::v2::ActuateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Actuate_, context, request, response);
}

void VAL::Stub::experimental_async::Actuate(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest* request, ::kuksa::val::v2::ActuateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Actuate_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::Actuate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::ActuateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Actuate_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::Actuate(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest* request, ::kuksa::val::v2::ActuateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Actuate_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::Actuate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::ActuateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Actuate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ActuateResponse>* VAL::Stub::AsyncActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::ActuateResponse>::Create(channel_.get(), cq, rpcmethod_Actuate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ActuateResponse>* VAL::Stub::PrepareAsyncActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ActuateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::ActuateResponse>::Create(channel_.get(), cq, rpcmethod_Actuate_, context, request, false);
}

::grpc::ClientWriter< ::kuksa::val::v2::ActuateRequest>* VAL::Stub::ActuateStreamRaw(::grpc::ClientContext* context, ::kuksa::val::v2::ActuateResponse* response) {
  return ::grpc_impl::internal::ClientWriterFactory< ::kuksa::val::v2::ActuateRequest>::Create(channel_.get(), rpcmethod_ActuateStream_, context, response);
}

void VAL::Stub::experimental_async::ActuateStream(::grpc::ClientContext* context, ::kuksa::val::v2::ActuateResponse* response, ::grpc::experimental::ClientWriteReactor< ::kuksa::val::v2::ActuateRequest>* reactor) {
  ::grpc_impl::internal::ClientCallbackWriterFactory< ::kuksa::val::v2::ActuateRequest>::Create(stub_->channel_.get(), stub_->rpcmethod_ActuateStream_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::kuksa::val::v2::ActuateRequest>* VAL::Stub::AsyncActuateStreamRaw(::grpc::ClientContext* context, ::kuksa::val::v2::ActuateResponse* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::kuksa::val::v2::ActuateRequest>::Create(channel_.get(), cq, rpcmethod_ActuateStream_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::kuksa::val::v2::ActuateRequest>* VAL::Stub::PrepareAsyncActuateStreamRaw(::grpc::ClientContext* context, ::kuksa::val::v2::ActuateResponse* response, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::kuksa::val::v2::ActuateRequest>::Create(channel_.get(), cq, rpcmethod_ActuateStream_, context, response, false, nullptr);
}

::grpc::Status VAL::Stub::BatchActuate(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::kuksa::val::v2::BatchActuateResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_BatchActuate_, context, request, response);
}

void VAL::Stub::experimental_async::BatchActuate(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest* request, ::kuksa::val::v2::BatchActuateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BatchActuate_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::BatchActuate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::BatchActuateResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_BatchActuate_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::BatchActuate(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest* request, ::kuksa::val::v2::BatchActuateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BatchActuate_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::BatchActuate(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::BatchActuateResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_BatchActuate_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::BatchActuateResponse>* VAL::Stub::AsyncBatchActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::BatchActuateResponse>::Create(channel_.get(), cq, rpcmethod_BatchActuate_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::BatchActuateResponse>* VAL::Stub::PrepareAsyncBatchActuateRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::BatchActuateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::BatchActuateResponse>::Create(channel_.get(), cq, rpcmethod_BatchActuate_, context, request, false);
}

::grpc::Status VAL::Stub::ListMetadata(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::kuksa::val::v2::ListMetadataResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_ListMetadata_, context, request, response);
}

void VAL::Stub::experimental_async::ListMetadata(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest* request, ::kuksa::val::v2::ListMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListMetadata_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::ListMetadata(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::ListMetadataResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_ListMetadata_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::ListMetadata(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest* request, ::kuksa::val::v2::ListMetadataResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListMetadata_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::ListMetadata(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::ListMetadataResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_ListMetadata_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ListMetadataResponse>* VAL::Stub::AsyncListMetadataRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::ListMetadataResponse>::Create(channel_.get(), cq, rpcmethod_ListMetadata_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::ListMetadataResponse>* VAL::Stub::PrepareAsyncListMetadataRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::ListMetadataRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::ListMetadataResponse>::Create(channel_.get(), cq, rpcmethod_ListMetadata_, context, request, false);
}

::grpc::Status VAL::Stub::PublishValue(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::kuksa::val::v2::PublishValueResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_PublishValue_, context, request, response);
}

void VAL::Stub::experimental_async::PublishValue(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest* request, ::kuksa::val::v2::PublishValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PublishValue_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::PublishValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::PublishValueResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_PublishValue_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::PublishValue(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest* request, ::kuksa::val::v2::PublishValueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PublishValue_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::PublishValue(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::PublishValueResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_PublishValue_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::PublishValueResponse>* VAL::Stub::AsyncPublishValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::PublishValueResponse>::Create(channel_.get(), cq, rpcmethod_PublishValue_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::PublishValueResponse>* VAL::Stub::PrepareAsyncPublishValueRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::PublishValueRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::PublishValueResponse>::Create(channel_.get(), cq, rpcmethod_PublishValue_, context, request, false);
}

::grpc::ClientReaderWriter< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>* VAL::Stub::OpenProviderStreamRaw(::grpc::ClientContext* context) {
  return ::grpc_impl::internal::ClientReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>::Create(channel_.get(), rpcmethod_OpenProviderStream_, context);
}

void VAL::Stub::experimental_async::OpenProviderStream(::grpc::ClientContext* context, ::grpc::experimental::ClientBidiReactor< ::kuksa::val::v2::OpenProviderStreamRequest,::kuksa::val::v2::OpenProviderStreamResponse>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest,::kuksa::val::v2::OpenProviderStreamResponse>::Create(stub_->channel_.get(), stub_->rpcmethod_OpenProviderStream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>* VAL::Stub::AsyncOpenProviderStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>::Create(channel_.get(), cq, rpcmethod_OpenProviderStream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>* VAL::Stub::PrepareAsyncOpenProviderStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderWriterFactory< ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>::Create(channel_.get(), cq, rpcmethod_OpenProviderStream_, context, false, nullptr);
}

::grpc::Status VAL::Stub::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::kuksa::val::v2::GetServerInfoResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetServerInfo_, context, request, response);
}

void VAL::Stub::experimental_async::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest* request, ::kuksa::val::v2::GetServerInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::GetServerInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::GetServerInfoResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, std::move(f));
}

void VAL::Stub::experimental_async::GetServerInfo(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest* request, ::kuksa::val::v2::GetServerInfoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, reactor);
}

void VAL::Stub::experimental_async::GetServerInfo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::kuksa::val::v2::GetServerInfoResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetServerInfo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetServerInfoResponse>* VAL::Stub::AsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::GetServerInfoResponse>::Create(channel_.get(), cq, rpcmethod_GetServerInfo_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::kuksa::val::v2::GetServerInfoResponse>* VAL::Stub::PrepareAsyncGetServerInfoRaw(::grpc::ClientContext* context, const ::kuksa::val::v2::GetServerInfoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::kuksa::val::v2::GetServerInfoResponse>::Create(channel_.get(), cq, rpcmethod_GetServerInfo_, context, request, false);
}

VAL::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::GetValueRequest, ::kuksa::val::v2::GetValueResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::GetValueRequest* req,
             ::kuksa::val::v2::GetValueResponse* resp) {
               return service->GetValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::GetValuesRequest, ::kuksa::val::v2::GetValuesResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::GetValuesRequest* req,
             ::kuksa::val::v2::GetValuesResponse* resp) {
               return service->GetValues(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[2],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VAL::Service, ::kuksa::val::v2::SubscribeRequest, ::kuksa::val::v2::SubscribeResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::SubscribeRequest* req,
             ::grpc_impl::ServerWriter<::kuksa::val::v2::SubscribeResponse>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[3],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< VAL::Service, ::kuksa::val::v2::SubscribeByIdRequest, ::kuksa::val::v2::SubscribeByIdResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::SubscribeByIdRequest* req,
             ::grpc_impl::ServerWriter<::kuksa::val::v2::SubscribeByIdResponse>* writer) {
               return service->SubscribeById(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::ActuateRequest, ::kuksa::val::v2::ActuateResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::ActuateRequest* req,
             ::kuksa::val::v2::ActuateResponse* resp) {
               return service->Actuate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[5],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< VAL::Service, ::kuksa::val::v2::ActuateRequest, ::kuksa::val::v2::ActuateResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReader<::kuksa::val::v2::ActuateRequest>* reader,
             ::kuksa::val::v2::ActuateResponse* resp) {
               return service->ActuateStream(ctx, reader, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::BatchActuateRequest, ::kuksa::val::v2::BatchActuateResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::BatchActuateRequest* req,
             ::kuksa::val::v2::BatchActuateResponse* resp) {
               return service->BatchActuate(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::ListMetadataRequest, ::kuksa::val::v2::ListMetadataResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::ListMetadataRequest* req,
             ::kuksa::val::v2::ListMetadataResponse* resp) {
               return service->ListMetadata(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[8],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::PublishValueRequest, ::kuksa::val::v2::PublishValueResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::PublishValueRequest* req,
             ::kuksa::val::v2::PublishValueResponse* resp) {
               return service->PublishValue(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[9],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< VAL::Service, ::kuksa::val::v2::OpenProviderStreamRequest, ::kuksa::val::v2::OpenProviderStreamResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             ::grpc_impl::ServerReaderWriter<::kuksa::val::v2::OpenProviderStreamResponse,
             ::kuksa::val::v2::OpenProviderStreamRequest>* stream) {
               return service->OpenProviderStream(ctx, stream);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VAL_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VAL::Service, ::kuksa::val::v2::GetServerInfoRequest, ::kuksa::val::v2::GetServerInfoResponse>(
          [](VAL::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::kuksa::val::v2::GetServerInfoRequest* req,
             ::kuksa::val::v2::GetServerInfoResponse* resp) {
               return service->GetServerInfo(ctx, req, resp);
             }, this)));
}

VAL::Service::~Service() {
}

::grpc::Status VAL::Service::GetValue(::grpc::ServerContext* context, const ::kuksa::val::v2::GetValueRequest* request, ::kuksa::val::v2::GetValueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::GetValues(::grpc::ServerContext* context, const ::kuksa::val::v2::GetValuesRequest* request, ::kuksa::val::v2::GetValuesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::Subscribe(::grpc::ServerContext* context, const ::kuksa::val::v2::SubscribeRequest* request, ::grpc::ServerWriter< ::kuksa::val::v2::SubscribeResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::SubscribeById(::grpc::ServerContext* context, const ::kuksa::val::v2::SubscribeByIdRequest* request, ::grpc::ServerWriter< ::kuksa::val::v2::SubscribeByIdResponse>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::Actuate(::grpc::ServerContext* context, const ::kuksa::val::v2::ActuateRequest* request, ::kuksa::val::v2::ActuateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::ActuateStream(::grpc::ServerContext* context, ::grpc::ServerReader< ::kuksa::val::v2::ActuateRequest>* reader, ::kuksa::val::v2::ActuateResponse* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::BatchActuate(::grpc::ServerContext* context, const ::kuksa::val::v2::BatchActuateRequest* request, ::kuksa::val::v2::BatchActuateResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::ListMetadata(::grpc::ServerContext* context, const ::kuksa::val::v2::ListMetadataRequest* request, ::kuksa::val::v2::ListMetadataResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::PublishValue(::grpc::ServerContext* context, const ::kuksa::val::v2::PublishValueRequest* request, ::kuksa::val::v2::PublishValueResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::OpenProviderStream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::kuksa::val::v2::OpenProviderStreamResponse, ::kuksa::val::v2::OpenProviderStreamRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status VAL::Service::GetServerInfo(::grpc::ServerContext* context, const ::kuksa::val::v2::GetServerInfoRequest* request, ::kuksa::val::v2::GetServerInfoResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace kuksa
}  // namespace val
}  // namespace v2

