# mylayer
IMAGE_INSTALL:append = " util-scripts"

# Devel recipes
IMAGE_INSTALL:append = " cmake raspi-utils raspi-gpio spitools can-utils libsocketcan ntp grpc protobuf i2c-tools v4l-utils gcc-sanitizers"

# Python 3 packages
IMAGE_INSTALL:append = " python3-opencv python3-tomllib python3-pip"

# QT recipes
IMAGE_INSTALL:append = " qtbase qtmultimedia qtquick3d qtdeclarative qtwayland qtserialbus qtpositioning"

# Kuksa recipes
IMAGE_INSTALL:append = " kuksa-databroker kuksa-can-provider kuksa-client"

# RPI Hailo
IMAGE_INSTALL:append = " hailo-pci hailortcli hailo-firmware libhailort packagegroup-hailo-hailort pyhailort"

# RPI Camera
IMAGE_INSTALL:append = " rpi-libcamera rpicam-apps pipewire opencv"

# Touchscreen overlay for RPI5
RPI_KERNEL_DEVICETREE_OVERLAYS:append = "overlays/vc4-kms-dsi-waveshare-panel.dtbo"

DISTRO_FEATURES:append = " systemd"

KERNEL_SPLIT_MODULES = "0"

IMAGE_ROOTFS_SIZE = "73400320"

LICENSE_FLAGS_ACCEPTED = "commercial"

PACKAGECONFIG:append:pn-opencv = " gtk libav"

# Config.txt and Overlays
ENABLE_I2C = "1"
KERNEL_MODULE_AUTOLOAD:rpi:append = " i2c-dev i2c-bcm2708"
ENABLE_CAN = "1"
CAN_OSCILLATOR = "8000000"
VIDEO_CAMERA  = "1"
RASPBERRYPI_CAMERA_V3 = "1"

PREFERRED_PROVIDER_libcamera ?= "rpi-libcamera"

PARALLEL_MAKE = "-j 8"
BB_NUMBER_THREADS = "16"
SSTATE_DIR = "${HOME}/sstate-cache"
DL_DIR = "${HOME}/downloads"
INHERIT = "rm_work"
RM_OLD_IMAGE = "1"

#SDKMACHINE = "aarch64"
