IMAGE_INSTALL:append = " cmake"
IMAGE_INSTALL:append = " qtbase qtmultimedia qtquick3d qtdeclarative"

BB_NUMBER_THREADS = "16"
SSTATE_DIR = "${HOME}/sstate-cache"
DL_DIR = "${HOME}/downloads"
INHERIT = "rm_work"
RM_OLD_IMAGE = "1"
