# mylayer
IMAGE_INSTALL:append = " util-scripts"

# Devel recipes
IMAGE_INSTALL:append = "  cmake raspi-utils raspi-gpio spitools can-utils libsocketcan ntp"

# QT recipes
IMAGE_INSTALL:append = " qtbase qtmultimedia qtquick3d qtdeclarative qtwayland qtserialbus qtpositioning"

# Kuksa recipes
IMAGE_INSTALL:append = " kuksa-databroker kuksa-can-provider kuksa-client"

BB_NUMBER_THREADS = "16"
SSTATE_DIR = "${HOME}/sstate-cache"
DL_DIR = "${HOME}/downloads"
INHERIT = "rm_work"
RM_OLD_IMAGE = "1"
