[core]
require-input=false
idle-time=0
modules=systemd-notify.so
activate-by-default=false

[shell]
locking=false
panel-position=none

# A display is connected to HDMI-A-1 and needs to be rotated 90 degrees
# to have a proper orientation of the homescreen.  For example, the 'eGalax'
# display used in some instances.
[output]
name=HDMI-A-1
transform=rotate-90

# A display is connected to HDMI-A-1 and needs to be rotated 90 degrees
# to have a proper orientation of the homescreen.  For example, the 'eGalax'
# display used in some instances.
[output]
name=HDMI-A-2
transform=rotate-90

[output]
name=DSI-1
mode=fullscreeN
transform=rotate-90

[autolaunch]
path=/usr/bin/qtApp
