name: Code Formatter

on:
  pull_request:
    types: [opened, synchronize, reopened]
#    branches-ignore:
#      - main
    path:
      - 'apps/Cluster'

jobs:
  formatter:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: format

    steps:
      - name: Fetching repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Log In to GHCR
        run: echo "${{ secrets.CLANG_KEY }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get C/C++ files
        id: changed_files
        run: echo "FILES=$(git diff --name-only HEAD~1 HEAD | grep -P '\.(c|cpp|h|hpp)(?!.)')" >> $GITHUB_OUTPUT

      - name: Run the llvm docker with clang-format
        run: ./formatter.sh ${{ steps.changed_files.outputs.files }}

