name: Code Formatter

on:
  push:
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'

  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**/*.c'
      - '**/*.cpp'
      - '**/*.h'
      - '**/*.hpp'

jobs:
  formatter:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: format

    steps:
      - name: Fetching repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2

      - name: Build Docker Container
        run: docker build -t $DOCKER_TAG ./actions/formatter

      - name: Run formatt script
        env:
          BEFORE: ${{ github.event.before }}
          AFTER: ${{ github.event.after }}
          EVENT: ${{ github.event_name }}
        run: bash ./actions/formatter/formatter.sh
