name: RaspSSH

on:

  workflow_dispatch:

jobs:

  rasp_ssh:

    runs-on: ubuntu-latest

    steps:
      - name: SSH
        run: ssh seame@10.21.220.161 -p 22

      - name: Run Echo
        run: echo Hello
