name: Requirements Trace

on:
  pull_request:

jobs:
  traceability:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.OTF_KEY }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run OpenFastTrace (with html)
        run: |
          docker run --rm \
            -v "$PWD":/repo \
            ghcr.io/seame-pt/team2_theyseame_rollin/oft:latest \
            trace -o html -f /repo/pr_trace_report.html src/ requirements/
      
      - name: Upload trace report
        uses: actions/upload-artifact@v4
        with:
          name: trace-report
          path: pr_trace_report.html
